### ISSUE TITLE
Use custom decoder and encoder in `JsonBone`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#1064]
I want to store a `datetime` object in a `JsonBone`. But this isn't serializable.
Can we use the `preprocessJsonObject` and `jsonDecodeObjectHook` from the `tasks` module here too?

**Comment by phorward** [comment]
> Can we use the `preprocessJsonObject` and `jsonDecodeObjectHook` from the `tasks` module here too?

Meanwhile with #1016, these functions where renamed and improved.
My proposal would be in #1072 to provide a `utils.json`-module with the functions `dumps` and `loads` implementing this special conversions.

**Comment by phorward** [comment]
fixed by #1072
