### ISSUE TITLE
New Icons set

### ISSUE THREAD

**Issue by akelch** [viur-framework/viur-core#1068]
Switch to bootstrap icons:
 {
      "file-system": "folder-fill",
      "users": "people-fill",
      "user": "person-fill",
      "dashboard": "grid-3x3-gap-fill",
      "trash": "trash-fill",
      "interface": "shuffle",
      "hierarchy": "diagram-2-fill",
      "icon-settings": "gear-fill",
      "icon-hashtag": "hash",
      "icon-list": "list-ul"
}

next admin 4.1.2 will support oldicons till 4.2.0

**Comment by phorward** [comment]
Fixed by #1069
