### ISSUE TITLE
Implement `UidBone`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#1117]
@ArneGudermann we talked about this already in a viur-shop meeting. ([Usecase](https://github.com/viur-framework/viur-shop/blob/9aeb5536a9e9fbd348c359a7f4f3520b909d5f0a/src/viur/shop/skeletons/order.py#L56-L61))

This bone should generate a unique, new identifier according to a specifc scheme

**Comment by phorward** [comment]
Fixed by #1131
