### ISSUE TITLE
compute not working with keybones.

### ISSUE THREAD

**Issue by akelch** [viur-framework/viur-core#1138]
compute parameter will be ignored by keybone

**Comment by ArneGudermann** [comment]
I know because the Keybone don't call the `unserialize` or `serialize` methods. Let's talk about this in the viur-meeting on friday

**Comment by sveneberth** [comment]
@ArneGudermann Please outsource the compute logic from `BaseBone.serialize()` to sth like `BaseBone.serialize_compute()` as discussed in the ViUR meeting.

**Comment by phorward** [comment]
Might this become resolved by #1204?

**Comment by phorward** [comment]
Should be fixed by #1145
