### ISSUE TITLE
`PhoneBone` required

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#1155]
I need a `PhoneBone`, which accepts only valid phone numbers, including international ones.

Requirements:
- subclass of `StringBone`, type `"str.phone"` (likewise `"str.email"`)
- Accept phone numbers of the format "0123 45678", "+49 123 45678", "+49-123-45678", "0049 123 45678" (maybe there's standard regex for this)
- Automatically correct phone-numbers without country prefix, so "0123" becomes "+49 123" (configurable)
- Can also be used for fax numbers (in Germany, this is currently a very important feature)

**Comment by sveneberth** [comment]
You could just use a `NumericBone` and `<sl-range/>`:

[![Meme](https://img-9gag-fun.9cache.com/photo/aOYr6LE_700bwp.webp)](https://9gag.com/gag/aOYr6LE)

<sub>_* irony off *_</sub>

**Comment by phorward** [comment]
#1205 merged.
