### ISSUE TITLE
`BooleanBone`'s `defaultValue` cannot be a `callable`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#1178]
The validation allows only bool, if you provide a `callable` (that returns a boolean) a `TypeError` is raised

https://github.com/viur-framework/viur-core/blob/33b85bea33d529a3caef58bb8c6edfc2b8a8256c/src/viur/core/bones/boolean.py#L26C80-L26C111

**Comment by phorward** [comment]
Fixed by #1274
