### ISSUE TITLE
Fix xml renderer

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#1191]
The xml renderer was always left behind in the past and sometimes has errors (such as [this undefined symbol `render`](https://github.com/viur-framework/viur-core/blob/main/src/viur/core/render/xml/user.py#L12C22-L12C28))

Maybe in the future the html renderer can also inherit from the xml renderer and some parts can be moved.

**Comment by phorward** [comment]
> Maybe in the future the html renderer can also inherit from the xml renderer and some parts can be moved.

I see this as part of #1071 and would generally advise to drop the renderer entirely for now, and re-implement it later on demand using a master renderer constructing JSON-serializable objects which simply is dumped to the specific target format, like JSON/MsgPack or even XML.
