### ISSUE TITLE
Accessing RelSkel values the old way is not possible

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#12]
Hello,
in the past I was able to access a relationalBones' destination values this way:
```python
tokSkel["user"]["dest"]["key"]
```

Due to the new SkeletonValues class, this is not possible anymore. I did change it to according to the following diff, but this is only a work-around, and I know that it's bad.
```diff
--- a/skeleton.py
+++ b/skeleton.py
@@ -70,6 +70,12 @@ class SkeletonValues(object):
                self.accessedValues = {}
                self.renderAccessedValues = {}
 
+       def __getitem__(self, item):
+               if item in self.accessedValues:
+                       return self.accessedValues[item]
+
+               return self.entity.get(item)
+
 
 class BaseSkeleton(object, metaclass=MetaBaseSkel):
        """
```

We definitely need a better solution for this! ViUR 2 projects must be held maintainable even when updated to ViUR 3.

**Comment by tsteinruecken** [comment]
This has been fixed in the shallowSkeletonWrapper branch
