### ISSUE TITLE
`RecordBone` with a `FileBone` inside having weak file references looses its content

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#1211]
This is a known problem with stacked RelationalBones, which is now documented in form of an issue.

This data model
```py
class SkelPartSkel(RelSkel):
	headline = StringBone(
            descr="Headline",
            searchable=True,
            languages=conf["viur.availableLanguages"]
	)

	image = FileBone(
            descr="Image",
            derive=conf["derives"]
	)

class SkelSkel(Skeleton):
        parts = RecordBone(
            descr="Abschnitt",
            format="$(headline.de)",
            multiple=True,
            using=SkelPartSkel
	)
```
stacks a `FileBone` in a multiple `RecordBone`.

Files, that are directly uploaded to the `image` bone in this case (without choosing it from the File module) are indicated as `weak`. Because the current design of ViUR does not support stacked bones, the weak file referencing doesn't apply in this case, and the file is being removed after a while.

**Comment by sveneberth** [comment]
I have just come across this condition. It confuses me.

https://github.com/viur-framework/viur-core/blob/3a681bc93e17d288f31345140bc519201a0f5e46/src/viur/core/bones/record.py#L163-L164

That would mean that blobs are only locked if they are in a searchable record bone. That's stupid.

Maybe it is the reason and just needs to be removed

**Comment by sveneberth** [comment]
Well, it's my fault.

duringDthe refactoring I must have copied the code from `getSearchTags` but not adapted it enough for `getReferencedBlobs`. This also explains why the variable is called `tag` and not `file_key`...

I'll create a PR then.
