### ISSUE TITLE
add/edit with pre-filled information requires for a "report no errors"-bounce

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#1220]
This issue is a little bit hard to describe... in some cases, the admin calls a module's add or edit function within a context, which pre-fills some bones e.g. a RelationalBone with `mybone.dest.key=somekey` and should validate them.

Depending on the skeleton, this might already lead in a creation or edit of the entry on initial load.

For this, there should be a special bounce-flag, which does the same as bounce=true, but without error reporting. So the input is parsed into the skeleton and returned as far as possible, but there should be no error reporting, this is done when "Save" is being hit.

Proposal:
1. `bounce=true` should do the same as now, parse data, report errors, but don't save.
2. `bounce=silent` should do the same as `bounce=true`, but without returning errors.

**Comment by phorward** [comment]
Working test scenario:

## `skeletons/test.py`

```py
from viur.core import skeleton
from viur.core.bones import *


class TestSkel(skeleton.Skeleton):
    name = StringBone(
        descr="Name",
        required=True,
        defaultValue="Test",
    )
```
## `modules/test.py`
```py
from viur.core.prototypes import List


class Test(List):
    pass
```

## Reproduction

Call the vi-admin in an empty tab using http://localhost:8080/vi/s/main.html#/db/test/add?name=Hello, an entry with name "Hello" is immediately created.

**Comment by phorward** [comment]
let's talk about it again tomorrow in the ViUR meeting, because I think this bounce=silent or something is kind of crap, because bounce is a boolean and we actually wanted to get rid of it - if you look at it from the REST API perspective - rather than complicate it even more.

I have now also built a simple test case (see above) where you can see this immediately. I think that the admin tool should be changed here after all, namely to send bounce=true in the initial case and simply ignore the errors, if any occur. Because you would have to install the bounce=silent anyway, and whether you do it this way or without complicating the core would be almost the same in the end, wouldn't it?

Translated with DeepL.com (free version)

**Comment by phorward** [comment]
Replaced/move into https://github.com/viur-framework/vi-admin/issues/49

**Comment by sveneberth** [comment]
> Replaced/move into [viur-framework/vi-admin#49](https://github.com/viur-framework/vi-admin/issues/49)

@phorward YFI, you can [transfer issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/transferring-an-issue-to-another-repository) to other repos
