### ISSUE TITLE
viur-core's `@jinjaGlobalFilter` `urlencode` shadows Jinja's `urlencode` filter

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#1255]
https://github.com/viur-framework/viur-core/blob/dd0431bc14c2a2b897f2f54de092cac45b0d5e71/src/viur/core/render/html/env/viur.py#L462-L478

https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.urlencode

IMO we could completely remove the smaller `viur-core` implementation.

**Comment by phorward** [comment]
Fixed by #1271
