### ISSUE TITLE
skel.items() in Jinja always delivers empty values

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#192]
Hello!

This view-Template does only work when bones are accessed by skel[boneName]. The values item of the iterator is always empty.

```jinja2
{% extends "viur_base.html" %}

{% block content %}
	{% for key, value in skel.items() %}
		value always Emtpy: {{ key }} = {{ value }}<br>
		this perfectly Works: {{ key }} = {{ skel[key] }}<br>
	{% endfor %}
{% endblock %}
```

**Comment by tsteinruecken** [comment]
My guess is that it is not empty, it's something like <baseBoneInstance ...> which is interpreted as an html tag and therefore not shown. That's a side-effect of not creating a dictionary-copy of key --> html-render-prepared-value anymore and instead passing the original skeleton instance. Not sure what's the best solution for this (lot's of code inside the server and possibly projects rely on .items() to yield key-bone pairs) - either that's now how it works (we may add a new iter function valueItems() or the like) - or we may override the behaviour of items() if a render is attached (which may lead to some nasty bugs if code receives such a skeleton that it doesn't expect)

**Comment by tsteinruecken** [comment]
My proposal would now be to add an yieldBoneValues: bool = False to the items() function in SkeletonInstance so you can change this behavior if desired.
