### ISSUE TITLE
File Upload broken?

### ISSUE THREAD

**Issue by XeoN-GHMB** [viur-framework/viur-core#193]
File upload seems to be broken. Removing the timeout parameter allows the upload. Is this parameter still needed here?
/deploy/viur/core/modules/file.py", line 296, in initializeUpload
    uploadUrl = blob.create_resumable_upload_session(content_type=mimeType, size=size, timeout=60)
TypeError: create_resumable_upload_session() got an unexpected keyword argument 'timeout'

**Comment by tsteinruecken** [comment]
Should be resolved by using the latest google-cloud-storage, or isn't it?

**Comment by XeoN-GHMB** [comment]
using latest (1.35.1) google-cloud-storage resolves this problem.
