### ISSUE TITLE
Is the rootNode convention still used?

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-core#197]
We have fixed a bug #196 and found that rootNode is still used in some places e.g. fileNodeSkel and there is a fixme on [line 377](https://github.com/viur-framework/viur-core/blob/af8d9b920a45708f5ec33a07f16ce52f99a87a0e/modules/file.py#L377)

Is this going to be fixed soon?

**Comment by tsteinruecken** [comment]
Is this still a problem? @xnopasaranx

**Comment by sveneberth** [comment]
I think at least the mention that there's broken and unreachable code is important. The whole method looks strange to me, especially with the trailing underscores, and needs a revision.
