### ISSUE TITLE
Form Javascript is missing

### ISSUE THREAD

**Issue by tsteinruecken** [viur-framework/viur-core#199]
The javascript merging the date and time select inputs form https://github.com/viur-framework/viur-core/blob/master/template/editform_bone_date.html into the format the server expects on post is broken (https://github.com/viur-framework/viur-core/blob/master/resources/js/viur-forms.js). Relates to #187 .

**Comment by skoegl** [comment]
I do have ported updated viur-forms stuff in pipeline. Give me some time to craft a PR. Thank you!

**Comment by phorward** [comment]
Obsolete by newer developments and move into viur-base.
