### ISSUE TITLE
Filter by key of subordinated skeleton.

### ISSUE THREAD

**Issue by klaus-thorres** [viur-framework/viur-core#233]
Hi :)

Can someone help me with a problem, please.

I am using a skeleton with a relational bone and I want to use the ListFilter method of the associated module to filter by keys of the subordinated skeleton.

So I tried this line of code to archive this:
```
query.filter("venue.dest.key", "ahBydWhycG90dG1ldGFsbGVychILEgV2ZW51ZRiAgIDY2v2VCgw")
```
Also I tried other combinations with "\_\_key\_\_" instead of "key" and/or without ".dest". The result is always empty.
Filtering by other bone values than the key works properly.

What am I doing wrong?

My version of viur-core is [3af1fd303ae37810b3917746a0299940469dd093](https://github.com/viur-framework/viur-core/commit/3af1fd303ae37810b3917746a0299940469dd093).

**Comment by sveneberth** [comment]
Hey,
your key is encoded as string (in the legacy representation). This is necessary to provide clients a suitable representation, but you cannot use this string representation for filtering directly in queries. They key of a relation is stored as Key-object in the datastore, therefore you have to filter with the same/equal key-object.

You can use [from_legacy_urlsafe](https://googleapis.dev/python/datastore/latest/keys.html#google.cloud.datastore.key.Key.from_legacy_urlsafe) to decode the string: 
```python
query.filter("venue.dest.key", db.KeyClass.from_legacy_urlsafe("ahBydWhycG90dG1ldGFsbGVychILEgV2ZW51ZRiAgIDY2v2VCgw"))
```

**Comment by klaus-thorres** [comment]
Ok, now it runs smoothly. Thank You!
