### ISSUE TITLE
Rename db.Query.mergeExternalFilter into db.Query.updateFilter

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#258]
`db.Query.mergeExternalFilter` is almost used in cases where it hasn't to do anything with an "external" filtering. The naming is misleading. Please rename this function before ViUR3 final. `db.Query.updateFilter` is an appropriate naming because it requests a dict and updates the provided Query to it.

**Comment by tsteinruecken** [comment]
As viur-core has landed in production, the window for non-bugfix breaking changes is closed for 3.0.
Despite this, the name of this function is probably fine, it's uses are not. This relates to #142 -  if we call this updateFilter or mergeFilter is still up for debate from my side.

**Comment by phorward** [comment]
I didn't know about mergeFilter. I'm OK with this.
