### ISSUE TITLE
Provide a utils.unescapeString function

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#260]
3dfd5bd0952218c530e417cc162818daf35ba7e3 introduced a utils.unescapeString function in the past, and 438fd45a54acc078d10ecfcf27451ed259b98f44 reverted it. Why?

3dfd5bd0952218c530e417cc162818daf35ba7e3 was made because there was often the case that a stringBone or textBone value contained escaped special characters. This is okay, but there are many cases where the true value is needed, e.g. when it is passed to an interface or rendered by a flare-application which doesn't care about any special characters as they are inserted as TextNodes. In this case, the unescaping function has to be implemented for every case again, again and again. Why was this already existing function be removed?

Either `utils.unescapeString` will be made available again or the escaping of characters in stringBone and textBone should be removed.

**Comment by tsteinruecken** [comment]
Because escapeString is a destructive one-way function. There's no way back; neither is there a "true" value. Just try to enter "< &lt;" into a stringBone. escapeString is *not* an encoding. The real problem here is that stringBones are not quoted on the client-side (vi/admin). While the *try* to undo the escapeString function, they should apply real html.escape and unescape (if needed) so the core does not have to mess with it's value.

**Comment by phorward** [comment]
Aha.

I have the case now that the - in my eyes - broken values from a textBone in this case are transferred to an external software via a restful API, so now have to implement unescapeString on my own  each time I need the real value of a stringBone or textBone because ViUR core is not in the position to provide such a function and therefore it has to be copied, and copied and copied.

IMHO escaping string values is part of the HTML renderer, and values shouldn't be stored broken and modified by VIUR and used broken everywhere without providing a simple function to correct them like this one.

But okay, if this is the way which is wanted, copying functions and doing all the stuff every time again and again...

**Comment by phorward** [comment]
We will discuss about this issue next VIUR meetup.

**Comment by tsteinruecken** [comment]
Just discovered that github has the same "issue"; the Example should read as "< (less then sign) and &-l-t-; (the quoted form of it)".
There values are indeed "broken" - there should be more quoting (as said, quoting should happen client-side in Vi/Admin) - as currently done with textbones. If you have issues with textbones please provide me with a sample (afaik textbones should be fine?). What you're looking for is probably 
`from html import unescape`
`unescape("&lt;")`
but as said, that's *not* the inverse of our escapeString function - such an inverse can not exist.
Escaping/quoting is *intentionally* done upfront (and not in the html render) so embedding such values into html is fast (which is the main use case)

**Comment by phorward** [comment]
Superseded by #395
