### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-core#353]
I am not sure if something has changed on the SDK side, but without this entry in my requirements I now get an error when starting a project with dev_appserver (or when deployin to GAE)

For now this can just be added to the project requirements as a quick fix

googleapis-common-protos[grpc]==1.53.0 --hash=sha256:c075eddaa2628ab519e01b7d75b76e66c40eaa50fc52758d8225f84708950ef2

**Comment by tsteinruecken** [comment]
This has already been fixed in https://github.com/viur-framework/viur-core/commit/e58f46de17cd7477458bab1fc7b64a7715995d06  - it just hasn't been released yet (it's only in develop)

**Comment by sveneberth** [comment]
I think this issue is outdated, if not please re-open it.
