### ISSUE TITLE
pytz.timezone in the arguments of @callDeferred Fuctions

### ISSUE THREAD

**Issue by ArneGudermann** [viur-framework/viur-core#357]
If you pass "pytz.timezone" or "currentRequestData" as argument in a function and then call it with callDeferred you get a TypeError.
This error occurs because the function "preprocessJsonObject" cannot translate the argument correctly.

Possible fix:
`	elif isinstance(o,pytz.BaseTzInfo):
		return str(o)`

In https://github.com/viur-framework/viur-core/blob/579fc7835b773d9ed5af18c2502322861e3f20b7/core/tasks.py#L23

**Comment by ArneGudermann** [comment]
First attempt for a solution:
https://github.com/viur-framework/viur-core/blob/03e4faff0ed643030d5065485d8a78028798bb91/core/tasks.py#L23-L44

**Comment by phorward** [comment]
I think this relates to #486 ?

**Comment by phorward** [comment]
Resolved by #486
