### ISSUE TITLE
Replace utils.escapeString by html.escape

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#395]
Use Python standard library [html.escape](https://docs.python.org/3/library/html.html#html.escape) for this.

Questions to solve:
- Why is the string cropped AFTER escaping?
- Wouldn't it be better to implement a cut-off limitation to stringBone, and cut BEFORE escaping?

**Comment by sveneberth** [comment]
Cutting the string before escaping makes imo more sense.

```py
escapeString("<b>Lorem ipsum</b>", 25)
# &lt;b&gt;Lorem ipsum&lt;/
```
Otherwise it causes broken data (the incomplete HTML-tag) like above

**Comment by tsteinruecken** [comment]
1) To ensure, that the final string does not exceed the specified length (ie fits in 254 bytes)
2) If you have a nice (and fast) solution that prevents these incomplete tags from happening fine. But then we'll should probably also check that the user does not provide incomplete tags himself
3) html.escape and utils.escapeString do different things

**Comment by phorward** [comment]
Hello, I would like to bring this issue to an end.
This issue is linked to #500 as well.
