### ISSUE TITLE
htmlSerializer twice

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#4]
Hey there,

we have currently in modules the htmlSerializer.
First of all it's only a class, not a really ViUR-Module. Furthermore we have another [htmlSerializer class in the texBone](https://github.com/viur-framework/viur-core/blob/de9d1a12c70738b5e376b24a994718398f62f89d/bones/textBone.py#L34-L200). I thing one good implementation should be enough.

**Comment by tsteinruecken** [comment]
Uh.. the one in modules looks like an old artifact - it's not used anywhere. But we might want to consider switching to a prebuild solution (like bleach)

**Comment by phorward** [comment]
fixed by #61
