### ISSUE TITLE
Refactor/Extend `TextBone.getReferencedBlobs` for multiple + languages

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#503]
The case multiple + languages (`if self.multiple and self.languages:...`) in [`TextBone.getReferencedBlobs`](https://github.com/viur-framework/viur-core/blob/222de3385885b80c23c954d60788860b40194c33/core/bones/text.py#L306) is currently missing. Anyway the code can be refactored too.

Originally mentioned in https://github.com/viur-framework/viur-core/pull/490#pullrequestreview-1082257710

**Comment by phorward** [comment]
RelationalBones seem to have a simular problem, see #515

**Comment by phorward** [comment]
Fixed by #528
