### ISSUE TITLE
Support Google Authenticator or similar App as second factor

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#557]
In perspective, ViUR should support not only the X-VIUR-2FACTOR-TimeBasedOTP but also Google Authenticator or similar apps that are appropriately trained via a QR code.

**Comment by sveneberth** [comment]
... and security keys (YubiKeys) would be nice.

**Comment by cheeaza** [comment]
Maybe we can use this library for the otp generation: https://pyauth.github.io/pyotp/#

**Comment by ArneGudermann** [comment]
Maybe we can use #578 as a start for this?

**Comment by phorward** [comment]
Implemented by #578, linked to #816
