### ISSUE TITLE
Standardize several notations

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#7]
There are several places in ViUR where the same functionality or behavior has different notations, but conceptually means the same. This issue should be first used as a collector for these notations, which finally should be renamed or equalized to the same notation when version 3.0 is finalized, to avoid confusions especially for newcomers.

# limit, amount

## Problem
[mergeExternalFilter()](https://github.com/viur-framework/viur-core/blob/master/db.py#L819) uses *amount* as GET-parameter, but sets the limit of the query. Functions like [run()](https://github.com/viur-framework/viur-core/blob/master/db.py#L1414) and [fetch()](https://github.com/viur-framework/viur-core/blob/master/db.py#L1516) are using *limit* instead.

## Proposal
Use `limit` everywhere.

# ~~getSkel(), getEntry()~~

## Problem
~~In the HTML-renderer, [getSkel()](https://github.com/viur-framework/viur-core/blob/master/render/html/env/viur.py#L324) returns the structure, and [getEntry()](https://github.com/viur-framework/viur-core/blob/master/render/html/env/viur.py#L128) returns and entry (which normally is a skel!). There is also a getSkel() function in db.Query which returns a Skeleton, and not the structure.~~

## Proposal
- ~~Rename `getSkel()` to `getStructure()`~~
- ~~Rename `getEntry()` to `getSkel()`~~

Edit: This has been fixed with #48 
~~
# ~~add, edit, delete => onItemAdded, onItemEdited, onItemDeleted => addItemSuccess(), editItemSuccess(), deleteSuccess()~~

## ~~Problem~~

~~Why can't we call them just "edit", "add" and "delete" same as the actions they do?~~

## ~~Proposal~~

~~My proposal is to rename this~~

    ~~edit => self.onItemEdited(skel) => self.render.editItemSuccess(skel)~~
    ~~add => self.onItemAdded(skel) => self.render.addItemSuccess(skel)~~
    ~~delete => self.onItemDeleted(skel) => self.render.deleteSuccess(skel)~~

~~into this:~~

    ~~edit => self.onEdit(skel) => self.render.editSuccess(skel)~~
    ~~add => self.onAdd(skel) => self.render.addSuccess(skel)~~
   ~~ delete => self.onDelete(skel) => self.render.deleteSuccess(skel)~~

Edit: This was fixed by #39 

# ~~Variants of relationalBone have misleading names~~

## ~~Problem~~
~~Why are specialized versions of relationalBone not correctly sub-classed... treeDirBone(), treeItemBone(), fileBone()
See [here](https://github.com/viur-framework/viur-vi/blob/feature/viur3/bones/relational.py#L324)...~~

## ~~Proposal~~

- ~~`treeDirBone()` indicates itself as `relational.treedir`, should be `relational.tree.node`~~
- ~~`treeItemBone()` indicates itself as `relational.treeitem`, should be `relational.tree.leaf` and renamed into `treeLeafBone()`~~
- ~~... it makes then sense to provide a `treeItemBone()` which is just `relational.tree` to select both nodes and leafs...~~
- ~~`fileBone()` indicates itself as `treeitem.file`??????, should be `relational.tree.leaf.file`~~
- ~~`hierarchyBone()` indicates itself as just `relational` without speciality - IMHO this can be removed entirely and replaced by relationalBone().~~

Edit: This has been fixed by #49

**Comment by tsteinruecken** [comment]
For limit we have to ensure that no project out there has a bone named limit - that name must then be reserved. For getEntry and getSkel i think they're correctly named - getSkel returns the structure of that skeleton, getEntry an Entity from the datastore..

**Comment by phorward** [comment]
@tsteinruecken please let us discuss this in a ViUR round. I think it won't be a problem to forbid naming bones "limit" - I think I have one project where this is the case, so a renaming won't be a problem. And its important to make ViUR more convenient with its namings in several places.

**Comment by phorward** [comment]
Here's another one: In [List-prototypes](https://github.com/viur-framework/viur-core/blob/master/prototypes/list.py) and their specific renderer functions, there called:

- `self.render.editItemSuccess(skel)` 
- `self.render.addItemSuccess(skel)`
- `self.render.deleteSuccess(skel)` ???

why not deleteItemSuccess(), or why not editSuccess(), addSuccess() and deleteSuccess() to all??

**Comment by phorward** [comment]
For the last comment, thinking more over it, why can't we call them just "edit", "add" and "delete" same as the actions they do?

My proposal is to rename this

- edit => self.onItemEdited(skel) => self.render.editItemSuccess(skel)
- add => self.onItemAdded(skel) => self.render.addItemSuccess(skel)
- delete => self.onItemDeleted(skel) => self.render.deleteSuccess(skel)

into this:

- edit => self.onEdit(skel) => self.render.editSuccess(skel)
- add => self.onAdd(skel) => self.render.addSuccess(skel)
- delete => self.onDelete(skel) => self.render.deleteSuccess(skel)

**Comment by phorward** [comment]
I have new input for this!

# Variants of relationalBone have misleading names

## Problem
Why are specialized versions of relationalBone not correctly sub-classed... treeDirBone(), treeItemBone(), fileBone()
See [here](https://github.com/viur-framework/viur-vi/blob/feature/viur3/bones/relational.py#L324)...

## Proposal

- `treeDirBone()` indicates itself as `relational.treedir`, should be `relational.tree.node`
- `treeItemBone()` indicates itself as `relational.treeitem`, should be `relational.tree.leaf` and renamed into `treeLeafBone()`
- `fileBone()` indicates itself as `treeitem.file`??????, should be `relational.tree.leaf.file`

**Comment by phorward** [comment]
Hi, I've reopened this again because it collects several issues. #39 was the first part. More will follow.

**Comment by phorward** [comment]
I'd updated the initial comment in this issue. Please be patient for further pull requests that resolve all the issues as discussed in ViUR discussion from June 26.

**Comment by phorward** [comment]
getSkel(), getEntry() proposal resolved by #48

**Comment by phorward** [comment]
#49 fixes misleading relationalBone names
