### ISSUE TITLE
PasswordBone - die Übersetzung von "The password is too short. It requires for at least 8 characters." fehlt

### ISSUE THREAD

**Issue by ClaudiaSollinger** [viur-framework/viur-core#760]
PasswordBone - Check des Passwortes

Übersetzung von "The password is too short. It requires for at least 8 characters." fehlt

**Comment by sveneberth** [comment]
Hello @ClaudiaSollinger, can you please explain this problem in more detail?

You mean this translate string, right?
https://github.com/viur-framework/viur-core/blob/b9aedcb1ae7207e8b614c2f7882ebc82890381f1/core/bones/password.py#L53

Like any other translation in the core, there's only the `defaultText` set. If you need it in English or any other language, you have to add the translation to your project.
