### ISSUE TITLE
relationalBone(multiple=True) but with unique relations per destination

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#79]
Hi there,

I'm having a requirement for some kind of unique-Feature for relationalBone(multiple=True) bones, where multiple relations to different destination can be added, but only one relation for each target key is allowed.
In the current implementation, I can create multiple relations to the same destination entity.

How could this be implemented?
How could it be named? (I think `unique` is not the right wording, because it is used differently).

**Comment by sveneberth** [comment]
Interesting feature/idea!
I think we have to implement this as a new parameter `referencedBy` (or something like that). Valid values could be a positive int to limit the references from this kind or _-1_ for infinity. 
Maybe we need several severities for this: 
- Reference only n-times with the same using-skel-values 
- or only n-times in general, 	independently from the using-skel-values. 

The validation could count the entities in the viur-relations kind with the actually src-kind and dest-relation - this should be straightforward, or not?

**Comment by tsteinruecken** [comment]
Not sure what you actually trying to archive. You have Kind A and B, both with entities a and b. You add relations from Entity A-a to entities B-a and B-b. Do you want to prevent another entity like A-b to also reference any of B-a and B-b? Then use unique with SameValue. Or do you want to prevent A-a from referencing B-a twice within the same relation? Then just add an test to interBoneValidations.

**Comment by phorward** [comment]
@tsteinruecken please provide an example for this. I just want a relationalBone, where only one relation can be created for each target entity. E.g. in a userBone(), I currently can select the same user twice. This should be avoided by this bone, which either accepts the entry when it's currently not linked, or either replaced or rejects it when it's already there.
