### ISSUE TITLE
Generalize bone.fromClient() for multiple- and language-bones

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#8]
Hello,

I'm currently implementing a general ViUR export & importer for Google Spreadsheets. I found out, that it is a good choice to build pathes to values, like "relbone.key.0", "relbone.key.1" or also "txtbone.de" and "txtbone.en". This is very straightforward and works both to access values from a JSON-rendered structure but also to specify values for the `bone.fromClient()` function.

But then, I found out that when I name a multiple-string bone this way "strbone.0", "strbone.1", etc. it is not recognized by ViUR because it looks for a list of value in "strbone" only.

My proposal here would be to allow for both: a list may be available under "strbone", or the single entries could be specified as "strbone.0", "strbone1." etc. This logic is also the same for language-bones which are multiple, here the case is "strbone.en.0", "strbone.en.1" containing single values or "strbone.en" allowing for a list. Note, that for `relationalBone(multiple=True)`, this is done exactly this way, so there is a asymmetry between how `stringBone()` and how `relationalBone()` values are parsed.

This issue is only a proposal for a pull request that will follow when I have some time. I generally would like to revise all `bone.fromClient()` functions to work equally with the same notation. In my opinion, there is a lot of code in these functions which is very redudnant and could be cleaned up this way (regard, f.e. stringBone, which has branches for `if bone.multiple and not bone.languages` or `if not bone.multiple and bone.languages`... this is only both awkward and error-prone.

**Comment by tsteinruecken** [comment]
I agree, and unification is definitely on the list as the language wrapper has to be adopted by all bones. This difference of the API is due to the relationalBone explicitly guarantees the preservation of the order of its entries while stringBone does not (Though it currently does afaik). We should check if the http protocol / our framework guarantees to preserve the order if a parameter is given multiple times, then we can unify this.

**Comment by phorward** [comment]
resolved with latest master.
