### ISSUE TITLE
Make the second factor selectable. A user should not be forced to use the first one.

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#820]
A user can not currently select from several set up 2nd factors. I just noticed this when reviewing #578, after I had tested #802 the days. In [this loop](https://github.com/viur-framework/viur-core/blob/db9f81b9e9aa94dc08389fa468b69d52b41ea210/src/viur/core/modules/user.py#L996-L1005) the first 2FA that would be usable is always selected, and the user has to continue the login with that. The order is ultimately set by the developer. 
This should actually return a list of all methods possible for the user, then the user can select one and continue the login flow with it.
Until this is solved, we don't even need to start implementing backup codes. After all, you want to be able to select them when needed.

**Comment by phorward** [comment]
Isn't this part of #816 as well?

**Comment by sveneberth** [comment]
> Isn't this part of #816 as well?

Hmm. The one point can be interpreted like this. I have overseen it. I formulated it more clearly, I hope that was okay. 

Then I close this issues as a (partial) duplicate of #816
