### ISSUE TITLE
user-module must be exposed for html renderer to use getCurrentUser

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#83]
`getCurrentUser` uses the user-module in the default renderer context. But if there is no user-module in the html-renderer (which is mostly the default render) this method will always return None, which is quite unusable. Therefore the user-module must always be exposed for the html-renderer, even if you want not use the user-html-templates. 
https://github.com/viur-framework/viur-core/blob/fc73b290372ce53cbf1e16ef2d162c8199d5c722/utils.py#L199-L213

**Comment by tsteinruecken** [comment]
By default the user-module maps to all renders (html, vi, admin). So where did it break? Did you explicitly exclude it? If so why? In almost all projects there are modules that have no html frontend (like files). They still have to be there.
