### ISSUE TITLE
use shoelace icons for custom actions

### ISSUE THREAD

**Issue by XeoN-GHMB** [viur-framework/viur-core#851]
Since the new vi uses shoelace, the corresponding icons must be changed:
https://github.com/viur-framework/viur-core/blob/develop/src/viur/core/modules/user.py#L1057 to "trash"
https://github.com/viur-framework/viur-core/blob/develop/src/viur/core/modules/user.py#L1076 to "interface"

https://serene-allen-537100.netlify.app/components/icon/

**Comment by phorward** [comment]
fixed by #852
