### ISSUE TITLE
core 3.5.0rc3 does not deliver the requirements.txt anymore

### ISSUE THREAD

**Issue by XeoN-GHMB** [viur-framework/viur-core#860]
the viur-cli can no longer check the dependencies this way.
tox.ini is also missing

**Comment by phorward** [comment]
> the viur-cli can no longer check the dependencies this way.
Fixed by https://github.com/viur-framework/viur-core/pull/862

> tox.ini is also missing
Is this important? I wonder why they got into the old wheels.

**Comment by phorward** [comment]
Fixed by https://github.com/viur-framework/viur-core/pull/862
