### ISSUE TITLE
Unreachable Code in skeleton.py

### ISSUE THREAD

**Issue by cheeaza** [viur-framework/viur-core#880]
Hello,

there is unreachable code in the skeleton.py in the function unserialize:

https://github.com/viur-framework/viur-core/blob/20f16774f2cb356c5035d3ff6af0282f861498c8/src/viur/core/skeleton.py#L1249

**Comment by sveneberth** [comment]
I'm not sure if this is a bug or still to be implemented or just obsolete.

The skeletons work with lazy evaluation, meaning there is no unserialization that works at once. Or should there be a forced "unserialize all" mode, which is parameter controlled?

@cheeaza Do you have a use case or need for it?


What do @phorward and @ArneGudermann think? That would have been a thematic for the recent viur meeting :see_no_evil: 

<sub>

---

PS: Don't wonder about my edit; I just fixed your link and replaced it with a perma url. :smiley: </sub>

**Comment by cheeaza** [comment]
No, i don't  have any use case for it.
I just stumbled across it when I was revising my other pullrequest.

**Comment by phorward** [comment]
IMHO the entire function is obsolete. The `skeleton.py` is an important module that requires full refactoring, including PEP-8 and modularization. Keep this issue open in regards of any obsolete code that still lies there.
