### ISSUE TITLE
Refactoring `typing` imports / usage

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#958]
We have a [lot of `typing` imports](https://github.com/search?q=repo%3Aviur-framework%2Fviur-core%20%20%22from%20typing%20import%22&type=code) like `from typing import this, that, ...`

Sometimes they are really long:
https://github.com/viur-framework/viur-core/blob/8809c5077403462b89ea5105bcbfcbeed6c301f9/src/viur/core/skeleton.py#L12

I saw in other projects they import `typing` aliased with `t` (`ìmport typing as t`) and write `argument: t.Any`.
Maybe we should do this in the viur-core too. What do you think, should this be part of our coding conventions?

**Comment by ArneGudermann** [comment]
I think that's a good idea. Let's do it this way, it's much cleaner.

**Comment by sveneberth** [comment]
We should also decide for one task decorator syntax. Currently we have

this (where we import the entire `task` module):
https://github.com/viur-framework/viur-core/blob/09312ee545da8275c10834a1e92047bab62b7395/src/viur/core/skeleton.py#L1317

and this (where we import every member of the module):

https://github.com/viur-framework/viur-core/blob/09312ee545da8275c10834a1e92047bab62b7395/src/viur/core/securitykey.py#L114

**Comment by phorward** [comment]
We should use `t` for `Typing` and `tasks.*` for task-related decorators, but not for standard decorators.

**Comment by phorward** [comment]
fixed by #986
