### ISSUE TITLE
Make index to a BasicApplication or not (Reminder to evaluate)

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#99]
Currently the index-module mostly inherits from object (and the renderer is assigned as attribute) or from the defaultRenderer.
IMO it's much more proper to inherit the index-module from the BasicApplication and handle it like any other module.
This caused also to handle the index differently than a module. See here: https://github.com/viur-framework/server/pull/191

We have to test was is currently possible on a index-module, and what isn't (deferred-tasks, periodicTasks, ...).
Maybe is was only a problem in ViUR 2...

**Comment by tsteinruecken** [comment]
That's fine with me. If we make this mandatory we can remove some quirks from the server. However this is probably not something we can actually "fix" here - that has to be done on project-level and probably in viur-base
