### ISSUE TITLE
Removal of `UserSkel.gaeadmin`-bone?

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#996]
According to https://github.com/viur-framework/viur-core/blob/main/src/viur/core/modules/user.py#L626, the BooleanBone `gaeadmin` of UserSkel is never set, as this part was never ported from ViUR 2 to ViUR 3.

In our recent developments, we also hadn't any problems that this property is missing. Therefore my suggestion is to remove it entirely, as part of pull request #983.

**Comment by sveneberth** [comment]
Removed in https://github.com/viur-framework/viur-core/pull/983
